services:
  dev:
    image: dev
    build:
      context: .
      target: dev
      args:
        USER: ${USER}
    environment:
      - DISPLAY=${DISPLAY}
      - USER=${USER}
    volumes:
      - ./:/home/${USER}/dev/taey
      - ~/.claude:/${USER}/dev/taey/.claude
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  runtime:
    image: runtime
    build:
      context: .
      target: runtime
      args:
        USER: ${USER}
    environment:
      - DISPLAY=${DISPLAY}
      - USER=${USER}
    volumes:
      - ./:/home/${USER}/dev/taey
      - ~/.claude:/${USER}/dev/taey/.claude
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
